version: "3"
services:
  db:
    image: postgres:latest
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin4/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    restart: always
  app:
    image: rust:latest
    links:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    command: cargo run
  dashboard:
    image: grafana/grafana
    links:
      - app
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - db
    environment:
      - GF_PATHS_CONFIG=/var/lib/grafana/grafana.ini
